name: topmortarseller
description: Aplikasi untuk toko atau penjual produk Top Mortar.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.1+21

environment:
  sdk: "3.8.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  qr_code_scanner_plus: ^2.0.10+1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.0
  upgrader: ^11.2.0
  url_launcher: ^6.3.1
  money_formatter: ^0.0.6
  intl: ^0.19.0
  carousel_slider: ^5.1.1
  flutter_local_notifications: ^19.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  device_info_plus: ^9.0.3
  image_gallery_saver_plus: ^4.0.1
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/favicon/favicon_white.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/favicon/
